@startuml

!include $lib/$block.iuml
!include $lib/$term_block_3_level.iuml
!include $lib/$wire.iuml

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Рейки, модульное оборудование
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

' Рейка с автоматами техники + розеток
!ifdef RAIL_LO
!include _din_rail_lo.iuml
!endif

' Рейка с УЗО + автоматы освещения
!ifdef RAIL_MI
!include _din_rail_mi.iuml
!endif

' Рейка с клеммами + ввод
!ifdef RAIL_HI
!include _din_rail_hi.iuml
!endif


'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Соединения ввода
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!ifdef RAIL_HI && SHOW_INGRESS
r_hi:sd:w                      -> r_hi:vr:e                     $wire(Brown, "10")
r_hi:sd__n:w                   -> r_hi:vr__n:e                  $wire(Blue, "10")
!endif

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подключение УЗО к питанию
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!ifdef RAIL_HI && RAIL_MI && SHOW_INGRESS
r_mi:rccb_common:e             -> r_hi:vr:w                     $wire(Brown, "10")
r_mi:rccb_common__n:e          -> r_hi:vr__n:w                  $wire(Blue, "10")

'r_mi:rccb_wo_bathroom:e        -> r_hi:vr:w          $wire(Brown, "6")
'r_mi:rccb_wo_bathroom__n:e     -> r_hi:vr__n:w       $wire(Blue, "6")

'r_mi:rccb_wo_bathroom:e -> r_mi:rccb_common:e        $wire(Brown, "10")
'r_mi:rccb_wo_bathroom__n:e -> r_mi:rccb_common__n:e  $wire(Blue, "10")
!endif

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подключение автоматов к УЗО
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

!ifdef RAIL_LO && RAIL_MI
r_lo:cb_permanent:e            -> r_mi:rccb_common:w            $wire(Brown, "10")
!endif

!ifdef RAIL_LO && RAIL_MI
r_lo:cb_wo_bathroom:e          -> r_mi:rccb_wo_bathroom:w       $wire(Brown, "6")
!endif

!ifdef RAIL_MI
r_mi:rccb_common:w             -> r_mi:cb_l_room1:e             $wire(Brown, "6")
!endif

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
@enduml
