@startdot
!define RANKSEP 2

!define EXPANDED

!define RAIL_HI

!include $lib/$block.iuml
!include $lib/$device.iuml
!include $lib/$term_block_3_level.iuml
!include $lib/$wire.iuml
!include $lib/$corr.iuml
!include $lib/$cable_3wire.iuml
!include $lib/$cable_4wire.iuml


digraph box {

label="Подключение типовой\nсдвоенной группы света"
labelloc = "t"
fontname = "Helvetica"
fontsize = 28
rankdir  = "LR"

!ifndef RANKSEP
!define RANKSEP 2
!endif

graph [ ranksep=RANKSEP; ];


'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
' Устройства в щите
'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Питание
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHASE [label="АВ кухня коридор"]
N
PE

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Клеммники
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
subgraph cluster_r_hi {
  style=invis
  label="Клеммники"

  r_hi
  $block_start()
   $block_label_2("Клеммники<br/>2-уровневые")
   !include terminals/l_kitchen.iuml
   !include terminals/s_kitchen.iuml
  $block_end()
}



'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
' Кабели
'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Кабель на светильник
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
c_kitchen_l   $cable_4wire_power_alt("кабель<br/>свет кухня")

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Кабель на выключатель
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
c_kitchen_s   $cable_3wire("кабель<br/>выкл кухня")



'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
' Подключения в щите
'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подвод фазы с автомата на кабель к выключателю (постоянная фаза)
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHASE -> c_kitchen_s:i_brown                        $wire(Brown,        "1.5") [label="Фаза постоянная"]

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подключение проводов кабеля выключателя (коммутируемые фазы)
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
r_hi:s_kitchen__top:e -> c_kitchen_s:i_blue         $wire(Blue,         "1.5")
r_hi:s_kitchen__bot:e -> c_kitchen_s:i_yg           $wire(YellowGreen,  "1.5")

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Перемычки на клеммах
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
r_hi:s_kitchen__top:w -> r_hi:l_kitchen__top:w      $wire(Black,         "4") [label="Винтовая\nперемычка"]
r_hi:s_kitchen__bot:w -> r_hi:l_kitchen__bot:w      $wire(Black,         "4") [label="Винтовая\nперемычка"]



'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
' Подключения кабелей к щиту
'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение проводов до ламп к клеммам
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
r_hi:l_kitchen__top:e -> c_kitchen_l:l2:w          $wire(Red,           "1.5") [label="Фаза\nсвет 1"]
r_hi:l_kitchen__bot:e -> c_kitchen_l:l1:w          $wire(White,         "1.5") [label="Фаза\nсвет 2"]

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение провода от ламп к земле
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
N -> c_kitchen_l:n:w                               $wire(Blue,          "1.5")

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение PE от ламп к PE
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PE -> c_kitchen_l:pe:w                           $wire(YellowGreen,   "1.5")



'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
' Оконечные устройства
'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

SWITCH   $switch_double("Выключатель<br/>сдвоенный")
LIGHTS   $light_fixture_double("Светильник<br/>на 2 группы света")



'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
' Подключение оконечных устройств
'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение выключателей к кабелю (клавиши)
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
'c_kitchen_s:i_brown:e -> c_kitchen_s:i_blue:e [label="Клавиша выключателя"]
'c_kitchen_s:i_brown:e -> c_kitchen_s:i_yg:e   [label="Клавиша выключателя"]

c_kitchen_s:i_brown   -> SWITCH:y1a:e           $wire(Brown,         "1.5")
SWITCH:y1b:e          -> SWITCH:y2a:e           $wire(Brown,         "1.5")
c_kitchen_s:i_blue    -> SWITCH:x1b:w           $wire(Blue,          "1.5")
c_kitchen_s:i_yg      -> SWITCH:x2b:w           $wire(YellowGreen,   "1.5")


'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение ламп к кабелю
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
c_kitchen_l:l1:e -> LIGHTS:l1                   $wire(White,         "1.5")
c_kitchen_l:l2:e -> LIGHTS:l2                   $wire(Red,           "1.5")
c_kitchen_l:n:e  -> LIGHTS:n                    $wire(Blue,          "1.5")
c_kitchen_l:pe:e -> LIGHTS:pe                   $wire(YellowGreen,   "1.5")

}
@enddot
