@startmindmap

<style>
legend {
  BackgroundColor #FFEFE0
}
node {
  FontStyle Bold
  FontSize 18
  FontName "Jetbrains Mono"
  Padding 4
  Margin 4
  RoundCorner 10
}

'Neutral
.N {
  BackgroundColor #lightblue
}

'Switch disconnector
.SD {
  BackgroundColor #lightsalmon
}
'Voltage relay
.VR {
  BackgroundColor #LightPink
}
'Installation contactors
.IC {
  BackgroundColor #NavajoWhite
}
'Latching relays
.LR {
  BackgroundColor #NavajoWhite
}
.RCCB {
  BackgroundColor #thistle
}
.CB {
  BackgroundColor lightgreen
}
'Terminal
.T {
  BackgroundColor #lightyellow
}
'Terminal
.T1 {
  BackgroundColor #khaki
}
.T_IN {
  BackgroundColor #Wheat
}
'Wall outlet block
.W {
  BackgroundColor #gainsboro
}
'Wall outlet
.W {
  BackgroundColor #white
}
'Light group
.L {
}
'Consumer
.C {
  BackgroundColor #lightgray
}
.VVG {
  BackgroundColor #black
  FontColor #white
}
</style>

* QW1 выключатель нагрузки<<SD>>
  * KU1 реле напряжения<<VR>>

    * Q7 30mA общий      <<RCCB>>
      * свет    <<>>
        * Q7 N                        <<N>>
          * X01 свет балкон     <<T1>>
            * 3x1.5 | 01 | свет балкон     <<VVG>>
              *_ светильники            <<L>>
          * X03 свет кухня      <<T1>>
            * 4x1.5 | 03 | свет кухня      <<VVG>>
              *_ светильники            <<L>>
          * X07 свет коридор 1  <<T1>>
            * 4x1.5 | 07 | свет коридор 1  <<VVG>>
              *_ светильники            <<L>>
          * X08 свет коридор 2  <<T1>>
            * 4x1.5 | 08 | свет коридор 2  <<VVG>>
              *_ светильники            <<L>>
          * X11 свет комната 1  <<T1>>
            * 4x1.5 | 11 | свет комната 1  <<VVG>>
              *_ светильники            <<L>>
          * X13 свет комната 2  <<T1>>
            * 4x1.5 | 13 | свет комната 2  <<VVG>>
              *_ светильники            <<W>>
          * X15 свет комната 3  <<T1>>
            * 4x1.5 | 11 | свет комната 3  <<VVG>>
              *_ светильники            <<L>>
          * X17 свет туалет     <<T1>>
            * 4x1.5 | 17 | свет туалет     <<VVG>>
              *_ светильники            <<L>>
              *_ вентилятор             <<L>>
          * X19 свет ванная     <<T1>>
            * 4x1.5 | 19 | свет ванная     <<VVG>>
              *_ светильники            <<L>>
              *_ вентилятор             <<L>>
              *_ подсветка зеркала      <<L>>

        * Q91 6A(B) балкон            <<CB>>
          * X02 выкл балкон     <<T1>>
            * 3x1.5 | 02 | выкл балкон     <<VVG>>

        * Q92 6A(B) кухня коридор     <<CB>>
          * X04 выкл кухня      <<T1>>
            * 3x1.5 | 04 | выкл кухня      <<VVG>>
              * рамка 1 м.
                * выкл. 2 кл.
          * X05 выкл коридор 1.1<<T1>>
            * 3x1.5 | 05 | выкл коридор 1.1<<VVG>>
              * рамка 1 м.
                * перекл. 2 кл.
          * X06 выкл коридор 1.2<<T1>>
            * 3x1.5 | 06 | выкл коридор 1.2<<VVG>>
          * X09 выкл коридор 2.1<<T1>>
            * 3x1.5 | 09 | выкл коридор 2.1<<VVG>>
              * рамка 1 м.
                * перекл. 2 кл.
          * X10 выкл коридор 2.2<<T1>>
            * 3x1.5 | 10 | выкл коридор 2.2<<VVG>>

        * Q93 6A(B) комната 1         <<CB>>
          * X12 выкл комната 1  <<T1>>
            * 3x1.5 | 12 | выкл комната 1  <<VVG>>

        * Q94 6A(B) комната 2         <<CB>>
          * X14 выкл комната 2  <<T1>>
            * 3x1.5 | 14 | выкл комната 2  <<VVG>>

        * Q95 6A(B) комната 3         <<CB>>
          * X16 выкл комната 3  <<T1>>
            * 3x1.5 | 16 | выкл комната 3  <<VVG>>

        * Q96 6A(B) ванн туалет       <<CB>>
          * X18 выкл туалет     <<T1>>
            * 3x1.5 | 18 | выкл туалет     <<VVG>>
              * рамка 1 м.
                * выкл 1 кл.
          * X20 выкл ванная     <<T1>>
            * 3x1.5 | 20 | выкл ванная     <<VVG>>
              * рамка 1 м.
                * выкл 1 кл.

      * розетки <<>>

        * Q61 16A(B) роз кухня        <<CB>>
          * 3x2.5 | 61 | роз кухня       <<VVG>>
            * здесь можно перечислять структуру потребителей на линии, например, в порядке следования шлейфа
            * блок розеток 1 (2 розетки)<<WB>>
            * блок розеток 2 (2 розетки)<<WB>>

        * Q62 16A(B) роз .....        <<CB>>
          * 3x2.5 | 62 | роз .....       <<VVG>>
            * document me!

      * техника <<>>

        * Q71 10A(B) ...              <<CB>>
          * 3x2.5 | 71 | холодильник     <<VVG>>
            *_ холодильник
          * 3x2.5 | 72 | слаботочный щит <<VVG>>
            *_ слаботочный щит
        * Q73 25A(B) ...              <<CB>>
          * 3x4.0 | 73 | ................<<VVG>>
            *_ ?
    * Q8 10mA роз ванная <<RCCB>>
      * ....... <<>>
        * Q81 16A(B) роз ванная       <<CB>>
          * 3x2.5 | 81 | роз ванная      <<VVG>>
            * блок розеток 1 (2 розетки)<<WB>>
              *_ роз. стиралка?
              *_ роз. фен?

@endmindmap
