@startuml
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wire($color, $cross_section="2.5")
!if $cross_section == "1.5"
  !$penwidth=2
!else
  !if $cross_section == "2.5"
    !$penwidth=3
  !else
    !$penwidth=%intval($cross_section)
  !endif
!endif

!if $color == "White"
!$color=LightGray
!endif

[
penwidth=$penwidth, arrowhead=none, color="$color",
'!ifndef NO_WIRE_CROSS_SECTION
'xlabel="$cross_section"
'!endif
]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireBrown1_5()
[ arrowhead=none; penwidth=2; color="Brown" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireBrown2_5()
[ arrowhead=none; penwidth=2.5; color="Brown" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireBrown4()
[ arrowhead=none; penwidth=4; color="Brown" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireBrown6()
[ arrowhead=none; penwidth=6; color="Brown" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireBrown10()
[ arrowhead=none; penwidth=10; color="Brown" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireWhite1_5()
[ arrowhead=none; penwidth=2; color="LightGray" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireYellowGreen1_5()
[ arrowhead=none; penwidth=2; color="YellowGreen" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireBlue1_5()
[ arrowhead=none; penwidth=2; color="Blue" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireRed1_5()
[ arrowhead=none; penwidth=2; color="Red" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireBlack1_5()
[ arrowhead=none; penwidth=2; color="Black" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireBlack2_5()
[ arrowhead=none; penwidth=2.5; color="Black" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireBlack4()
[ arrowhead=none; penwidth=4; color="Black" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireBlack10()
[ arrowhead=none; penwidth=10; color="Black" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireBlue2_5()
[ arrowhead=none; penwidth=2.5; color="Blue" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireBlue4()
[ arrowhead=none; penwidth=4; color="Blue" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireBlue6()
[ arrowhead=none; penwidth=6; color="Blue" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireBlue10()
[ arrowhead=none; penwidth=10; color="Blue" ]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $wireYellow1_5()
[ arrowhead=none; penwidth=2; color="Gold" ]
!endprocedure

@enduml
