@startuml
!include $lib/$block.iuml
!include $lib/$modules.iuml

subgraph cluster_r_mi {
  style=invis
  {
  rank=same;

  r_mi
  $block_start()

    !include rccb/rccb_common.iuml
    $module_2u_rccb("Q8", rccb_wo_bathroom,  "роз ванная",            $model="ABB F202 16A 10mA (A)",  $bar_l_pos="left",  $bar_n_pos="left")

    $module_2u_rccb("Q9", rccb_wo_light,     "(резерв свет)",         $model="")

    $module_1u_cb("Q91",  cb_l_balcony,      "свет балкон",           $model="ABB S201 (B) 6A", $bar="l", $bar_pos="right")
    $module_1u_cb("Q92",  cb_l_kitchen,      "свет кухня коридор",    $model="ABB S201 (B) 6A", $bar="l", $bar_pos="both")
    $module_1u_cb("Q93",  cb_l_room1,        "свет комната 1",        $model="ABB S201 (B) 6A", $bar="l", $bar_pos="both")
    $module_1u_cb("Q94",  cb_l_room2,        "свет комната 2",        $model="ABB S201 (B) 6A", $bar="l", $bar_pos="both")
    $module_1u_cb("Q95",  cb_l_room3,        "свет комната 3",        $model="ABB S201 (B) 6A", $bar="l", $bar_pos="both")
    !include circuit_breakers/cb_l_bathroom.iuml

  $block_end()
  }
}

@enduml
