@startuml
!include _wiring_contents.iuml

' ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Кабели в начало коридора
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
subgraph cluster_corr_b {
  $corr(0)
  c_corr_b_1_s   $cable_3wire("выкл<br/>коридор<br/>начало<br/>1")
  c_corr_b_2_s   $cable_3wire("выкл<br/>коридор<br/>начало<br/>2")
}

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Кабели в конец коридора
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
subgraph cluster_corr_e {
  $corr(0)
  c_corr_e_1_s   $cable_3wire("выкл<br/>коридор<br/>конец<br/>1")
  c_corr_e_2_s   $cable_3wire("выкл<br/>коридор<br/>конец<br/>2")
}

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Кабели на светильники
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
c_corr_b_l       $cable_4wire_power_alt("коридор свет 1<br/>1")
c_corr_e_l       $cable_4wire_power_alt("коридор свет 2<br/>1")

' ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подключение кабелей 1 группы света к клеммам
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
r_hi:s_corr_1_1__top:e -> c_corr_b_1_s:i_blue     $wire(Blue,         "1.5")
r_hi:s_corr_1_1__bot:e -> c_corr_b_1_s:i_yg       $wire(YellowGreen,  "1.5")

r_hi:s_corr_1_2__top:e -> c_corr_e_1_s:i_blue     $wire(Blue,         "1.5")
r_hi:s_corr_1_2__bot:e -> c_corr_e_1_s:i_yg       $wire(YellowGreen,  "1.5")

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подключение кабелей 2 группы света к клеммам
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
r_hi:s_corr_2_1__top:e -> c_corr_b_2_s:i_blue:w   $wire(Blue,         "1.5")
r_hi:s_corr_2_1__bot:e -> c_corr_b_2_s:i_yg       $wire(YellowGreen,  "1.5")

r_hi:s_corr_2_2__top:e -> c_corr_e_2_s:i_blue:w   $wire(Blue,         "1.5")
r_hi:s_corr_2_2__bot:e -> c_corr_e_2_s:i_yg       $wire(YellowGreen,  "1.5")

' ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подсоединение проводов до ламп к клеммам
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
r_hi:l_corr_1__top:e -> c_corr_b_l:l2:w          $wire(Red,           "1.5")
r_hi:l_corr_1__bot:e -> c_corr_b_l:l1:w          $wire(White,         "1.5")

r_hi:l_corr_2__top:e -> c_corr_e_l:l2:w          $wire(Red,           "1.5")
r_hi:l_corr_2__bot:e -> c_corr_e_l:l1:w          $wire(White,         "1.5")

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подсоединение проводов от ламп к земле
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
N -> c_corr_b_l:n:w                            $wire(Blue,          "1.5")
N -> c_corr_e_l:n:w                            $wire(Blue,          "1.5")

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подсоединение PE от ламп к PE
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
PE -> c_corr_b_l:pe:w                          $wire(YellowGreen,   "1.5")
PE -> c_corr_e_l:pe:w                          $wire(YellowGreen,   "1.5")


' ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подсоединение ламп к кабелю
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
LAMP1_1  [label="Лампа"]
LAMP1_2  [label="Лампа"]
PE1 [label="Корпус"]
c_corr_b_l:l1:e -> LAMP1_1                     $wire(White,         "1.5")
c_corr_b_l:l2:e -> LAMP1_2                     $wire(Red,           "1.5")
c_corr_b_l:n:e  -> LAMP1_1                     $wire(Blue,          "1.5")
c_corr_b_l:n:e  -> LAMP1_2                     $wire(Blue,          "1.5")
c_corr_b_l:pe:e -> PE1                         $wire(YellowGreen,   "1.5")

LAMP2_1  [label="Лампа"]
LAMP2_2  [label="Лампа"]
PE2 [label="Корпус"]
c_corr_e_l:l1:e -> LAMP2_1                     $wire(White,         "1.5")
c_corr_e_l:l2:e -> LAMP2_2                     $wire(Red,           "1.5")
c_corr_e_l:n:e  -> LAMP2_1                     $wire(Blue,          "1.5")
c_corr_e_l:n:e  -> LAMP2_2                     $wire(Blue,          "1.5")
c_corr_e_l:pe:e -> PE2                         $wire(YellowGreen,   "1.5")

@enduml
