@startdot
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' EXPANDED
'
' SHOW_TERMINALS_WALL_OUTLETS
' SHOW_TERMINALS_LIGHTS
' SHOW_TERMINALS_BUTTONS
' SHOW_TERMINALS_SENSORS
' SHOW_TERMINALS_BUTTON_BACKLIGHTS
'
' SHOW_WIRING_OUTLETS
' SHOW_WIRING_LIGHTS
'
' SHOW_HOT
' SHOW_N
'
' SHOW_BRIDGES
' SHOW_JUMPERS
' SHOW_PATCHES
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'!define SHOW_BUSBARS
!include $lib/$block.iuml
!include $lib/$term_block_3_level.iuml
!include $lib/$wire.iuml


digraph box {

label    = "$label"
labelloc = "t"
fontname = "Helvetica"
fontsize = 28
rankdir  = "LR"

!ifndef RANKSEP
!define RANKSEP 2
!endif

graph [ ranksep=RANKSEP; ];

!include _wiring_contents.iuml

}
@enddot
