@startdot

!define RANKSEP 4

!define EXPANDED

!define RAIL_UP

!include $block.iuml
!include $term_block_3_level.iuml
!include $wire.iuml
!include $corr.iuml
!include $cable_3wire.iuml
!include $cable_4wire.iuml


digraph box {

fontname = "Helvetica"
rankdir  = "LR"

!ifndef RANKSEP
!define RANKSEP 2
!endif

graph [ ranksep=RANKSEP; ];

!include _wiring_80_3_way_switch__base.iuml

}
@enddot
