@startdot

!define RANKSEP 4

!define EXPANDED

!define RAIL_UP

!include $lib/$block.iuml
!include $lib/$term_block_3_level.iuml
!include $lib/$wire.iuml
!include $lib/$corr.iuml
!include $lib/$cable_3wire.iuml
!include $lib/$cable_4wire.iuml


digraph box {

label="Освещение в коридоре\n4 независимых выключателя\n2 кабеля из 4 не используется   "
fontname = "Helvetica"
rankdir  = "LR"

!ifndef RANKSEP
!define RANKSEP 2
!endif

graph [ ranksep=RANKSEP; ];

!include _wiring_80_3_way_switch__base.iuml

' ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подвод фазы с автомата
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
PHASE [label="АВ кухня коридор"]
'PHASE -> c_corr_b_1_s:i_brown                  $wire(Brown,         "1.5")
PHASE -> c_corr_b_2_s:i_brown                  $wire(Brown,         "1.5")
PHASE -> c_corr_e_1_s:i_brown                  $wire(Brown,         "1.5")
'PHASE -> c_corr_e_2_s:i_brown                  $wire(Brown,         "1.5")

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Шинка для неиспользованных проводов
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
UNUSED [label="Шинка для неиспользованных проводов (или PE)"]
UNUSED -> c_corr_b_1_s:i_brown                  $wire(Brown,         "1.5")
UNUSED -> c_corr_e_2_s:i_brown                  $wire(Brown,         "1.5")


' ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Перемычки на клеммах для светильников на кабеле 1
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
r1:s_corr_1_2__top:w -> r1:l_corr_1__top:w     $wire(Black,         "4")
r1:s_corr_1_2__bot:w -> r1:l_corr_1__bot:w     $wire(Black,         "4")

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Перемычки на клеммах для светильников на кабеле 2
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
r1:s_corr_2_1__top:w -> r1:l_corr_2__top:w     $wire(Black,         "4")
r1:s_corr_2_1__bot:w -> r1:l_corr_2__bot:w     $wire(Black,         "4")

' ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подсоединение выключателей к кабелям (клавиши)
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
c_corr_b_2_s:i_brown:e -> c_corr_b_2_s:i_blue:e [label="Клавиша выключателя"]
c_corr_b_2_s:i_brown:e -> c_corr_b_2_s:i_yg:e   [label="Клавиша выключателя"]

c_corr_e_1_s:i_brown:e -> c_corr_e_1_s:i_blue:e [label="Клавиша выключателя"]
c_corr_e_1_s:i_brown:e -> c_corr_e_1_s:i_yg:e   [label="Клавиша выключателя"]
'c_corr_e_2_s:i_brown:e -> c_corr_e_2_s:i_blue:e [label="Клавиша выключателя"]

}
@enddot
