@startdot
!define RANKSEP 2

!define EXPANDED

!define RAIL_HI

!include $lib/$block.iuml
!include $lib/$term_block_3_level.iuml
!include $lib/$wire.iuml
!include $lib/$corr.iuml
!include $lib/$cable_3wire.iuml
!include $lib/$cable_4wire.iuml


digraph box {

label="освещение ванной"
fontname = "Helvetica"
rankdir  = "LR"

!ifndef RANKSEP
!define RANKSEP 2
!endif

graph [ ranksep=RANKSEP; ];

!include _wiring_contents.iuml

' ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Кабель освещения
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
c_bathroom_l   $cable_4wire_power_alt("кабель 4x1.5мм2<br/>свет<br/>ванная")

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Кабель на выключатель
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
c_bathroom_s   $cable_3wire("кабель 3x1.5мм2<br/>выкл<br/>ванная")


' ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подвод фазы с автомата на кабель к выключателю (постоянная фаза)
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
PHASE [label="АВ ванная туалет"]
PHASE -> c_bathroom_s:i_brown                   $wire(Brown,        "1.5") [label="Фаза постоянная"]

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подвод фазы с автомата на кабель освещения (постоянная фаза)
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
PHASE [label="АВ ванная туалет"]
PHASE -> c_bathroom_l:l2                         $wire(Red,        "1.5") [label="Фаза постоянная"]

' ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подключение проводов кабеля выключателя (коммутируемые фазы)
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
r_hi:s_bathroom__top:e -> c_bathroom_s:i_blue       $wire(Blue,         "1.5") [label="Фаза коммутированная 1"]
r_hi:s_bathroom__bot:e -> c_bathroom_s:i_yg         $wire(YellowGreen,  "1.5") [label="Фаза коммутированная 2"]

' ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Перемычки на клеммах
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
r_hi:s_bathroom__top:w -> r_hi:l_bathroom__top:w      $wire(Black,         "4")
r_hi:s_bathroom__bot:w -> r_hi:l_bathroom__bot:w      $wire(Black,         "4")

' ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подсоединение проводов до ламп к клеммам
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
r_hi:l_bathroom__top:e -> c_bathroom_l:l1:w          $wire(White,         "1.5")

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подсоединение провода от ламп к земле
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
N -> c_bathroom_l:n:w                             $wire(Blue,          "1.5")

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подсоединение PE от ламп к PE
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
PE -> c_bathroom_l:pe:w                           $wire(YellowGreen,   "1.5")


' ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подсоединение ламп к кабелю
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
LAMP  [label="Лампа"]
VENT  [label="Вентилятор"]
MIRR  [label="Подсветка зеркала"]
'ENCL  [label="Корпус"]

c_bathroom_l:l1:e -> LAMP                        $wire(White,         "1.5")
c_bathroom_l:n:e  -> LAMP                        $wire(Blue,          "1.5")
c_bathroom_l:pe:e -> LAMP                        $wire(YellowGreen,   "1.5")

c_bathroom_l:l1:e -> VENT                        $wire(White,         "1.5")
c_bathroom_l:l2:e -> VENT                        $wire(Red,           "1.5")
c_bathroom_l:n:e  -> VENT                        $wire(Blue,          "1.5")
c_bathroom_l:pe:e -> VENT                        $wire(YellowGreen,   "1.5")

c_bathroom_l:l2:e -> MIRR                        $wire(Red,           "1.5")
c_bathroom_l:n:e  -> MIRR                        $wire(Blue,          "1.5")
c_bathroom_l:pe:e -> MIRR                        $wire(YellowGreen,   "1.5")

'c_bathroom_l:pe:e -> ENCL                        $wire(YellowGreen,   "1.5")

' ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Подсоединение выключателей к кабелю (клавиши)
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
c_bathroom_s:i_brown:e -> c_bathroom_s:i_blue:e [label="Клавиша выключателя"]

}
@enddot
