@startdot

!define RANKSEP 1

!define EXPANDED

!define RAIL_HI

!include $lib/$block.iuml
!include $lib/$term_block_3_level.iuml
!include $lib/$wire.iuml
!include $lib/$corr.iuml
!include $lib/$cable_3wire.iuml
!include $lib/$cable_4wire.iuml

!include $lib/$device.iuml
!include $lib/$block.iuml
!include $lib/$term_block_2_level.iuml


digraph box {

label="Освещение в коридоре\nПроходной выключатель"
labelloc = "t"
fontname = "Helvetica"
fontsize = 28
rankdir  = "LR"

graph [ ranksep=RANKSEP; ];



'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
' Устройства в щите
'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Питание
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHASE [label="АВ кухня коридор"]

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Клеммники
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
subgraph cluster_r_hi {
  style=invis
  label="Клеммники"

  r_hi
  $block_start()
   $block_label_2("Клеммники<br/>2-уровневые")

   !include terminals/s_corr_1_1_simple.iuml

  $block_end()
}

'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
' Кабели
'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Кабель в начало коридора
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
subgraph cluster_corr_b {
  $corr(0)
  c_corr_b_1_s   $cable_3wire("кабель<br/>3x1.5мм2<br/>выкл коридор")
}

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Кабель между выключателями
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
subgraph cluster_corr_с {
  $corr(0)
  c_corr         $cable_3wire("кабель<br/>3x1.5мм2<br/>между выкл коридор")
}

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Кабель на светильники
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
c_corr_b_l       $cable_4wire_power_alt("кабель<br/>3x1.5мм2<br/>свет коридор")


'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
' Подключения кабелей к щиту
'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подключение кабелей 1 группы света к клеммам
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
r_hi:s_corr_1_1__top:e -> c_corr_b_1_s:i_blue               $wire(Blue,         "1.5")
r_hi:s_corr_1_1__bot:e -> c_corr_b_1_s:i_yg                 $wire(YellowGreen,  "1.5")  [label="не исп."]

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение проводов до ламп к клеммам
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
r_hi:s_corr_1_1__top:w -> c_corr_b_l:l1:w                   $wire(White,         "1.5")
r_hi:s_corr_1_1__bot:w -> c_corr_b_l:l2:w                   $wire(Red,           "1.5") [label="не исп."]



'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение проводов от ламп к земле
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
N -> c_corr_b_l:n:w                                         $wire(Blue,          "1.5")

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение PE от ламп к PE
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PE -> c_corr_b_l:pe:w                                       $wire(YellowGreen,   "1.5")

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подвод фазы с автомата
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHASE -> c_corr_b_1_s:i_brown                               $wire(Brown,         "1.5")


'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
' устройства
'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

TBLOCK  $terminal_block_1_1("WAGO")
SW1     $switch_spdt("Переключатель<br/>коридор<br/>начало")
SW2     $switch_spdt_rev("Переключатель<br/>коридор<br/>конец")
LIGHTS1 $light_fixture_single("Светильники")

NOTE    [shape="box" label="Сюда можно подключить\nеще один выключатель в начале коридора,\nне проходной,\nдля управления второй группой света,\nнапример лампой ночного освещения,\nно наверное, такой выключатель\nв начале коридора не особо полезен"]

'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
' Подключение устройств
'███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение переключателя 1 к кабелю
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
c_corr_b_1_s:i_brown    -> SW1:x1                           $wire(Brown,        "1.5")
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение WAGO к кабелю
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
c_corr_b_1_s:i_blue     -> TBLOCK:x1                        $wire(Blue,         "1.5")
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение NOTE к кабелю
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
c_corr_b_1_s:i_brown    -> NOTE                             $wire(Brown,        "1.5")
c_corr_b_1_s:i_yg       -> NOTE                             $wire(YellowGreen,  "1.5")


'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение кабеля к переключателю 1
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SW1:y1a                 -> c_corr:i_blue                    $wire(Blue,         "1.5")
SW1:y1b                 -> c_corr:i_yg                      $wire(YellowGreen,  "1.5")
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение кабеля к WAGO
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TBLOCK:y1               -> c_corr:i_brown                   $wire(Brown,        "1.5")

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение переключателя 2 к кабелю
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
c_corr:i_blue           -> SW2:y1a                          $wire(Blue,         "1.5")
c_corr:i_yg             -> SW2:y1b                          $wire(YellowGreen,  "1.5")
c_corr:i_brown          -> SW2:x1:e                           $wire(Brown,        "1.5")

'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
' Подсоединение ламп к кабелю
'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
c_corr_b_l:l1:e         -> LIGHTS1:l                        $wire(White,        "1.5")
c_corr_b_l:n:e          -> LIGHTS1:n                        $wire(Blue,         "1.5")
c_corr_b_l:pe:e         -> LIGHTS1:pe                       $wire(YellowGreen,  "1.5")

}
@enddot
