@startuml
!procedure $cable_3wire($title)
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td align="text" bgcolor="#202020" border="1"><b><font color="white">$title</font></b></td></tr>
      <tr><td align="text" port="i_blue"  bgcolor="#ffffff" border="1">синий           <br align="left"/></td></tr>
      <tr><td align="text" port="i_brown" bgcolor="#ffffff" border="1">коричневый      <br align="left"/></td></tr>
      <tr><td align="text" port="i_yg"    bgcolor="#ffffff" border="1">жёлто-зеленый   <br align="left"/></td></tr>
    </table>
  >
]
!endprocedure
@enduml
