@startuml
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $cable_4wire($title)
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td align="text" bgcolor="#f0f0f0"   border="1">$title</td></tr>
      <tr><td align="text" port="i_red"    bgcolor="#ffffff" border="1">красный         <br align="left"/></td></tr>
      <tr><td align="text" port="i_yg"     bgcolor="#ffffff" border="1">жёлто-зеленый   <br align="left"/></td></tr>
      <tr><td align="text" port="i_blue"   bgcolor="#ffffff" border="1">синий           <br align="left"/></td></tr>
      <tr><td align="text" port="i_white"  bgcolor="#ffffff" border="1">белый           <br align="left"/></td></tr>
    </table>
  >
]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $cable_4wire_power_alt($title)
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td align="text" bgcolor="#f0f0f0"   border="1">$title</td></tr>
      <tr><td align="text" port="l2"       bgcolor="#ffffff" border="1">красный         <br align="left"/></td></tr>
      <tr><td align="text" port="pe"       bgcolor="#ffffff" border="1">жёлто-зеленый   <br align="left"/></td></tr>
      <tr><td align="text" port="n"        bgcolor="#ffffff" border="1">синий           <br align="left"/></td></tr>
      <tr><td align="text" port="l1"       bgcolor="#ffffff" border="1">белый           <br align="left"/></td></tr>
    </table>
  >
]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
@enduml
