@startuml
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $device_1x($title, $port, $port_label)
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td align="text"               border="1" bgcolor="wheat">$title</td></tr>
      <tr><td align="text" port="common" border="1"                >общий<br align="left"/></td></tr>
      <tr><td align="text" port="$port"  border="1"                >$port_label<br align="left"/></td></tr>
    </table>
  >
]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $device_1o($title)
'$device_1x($title="$title", "output", "выход")
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td align="text" bgcolor="wheat"   border="1">$title</td></tr>
      <tr><td align="text" port="common" border="1">общий<br align="left"/></td></tr>
      <tr><td align="text" port="output"  border="1">выход<br align="left"/></td></tr>
    </table>
  >
]
!endprocedure
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!procedure $device_2o($title)
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td align="text" bgcolor="wheat"   border="1">$title</td></tr>
      <tr><td align="text" port="common" border="1">общий<br align="left"/></td></tr>
      <tr><td align="text" port="output_1"  border="1">выход 1<br align="left"/></td></tr>
      <tr><td align="text" port="output_2"  border="1">выход 2<br align="left"/></td></tr>
    </table>
  >
]
!endprocedure

' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

!procedure $device_1i($title)
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td align="text" bgcolor="wheat"   border="1">$title</td></tr>
      <tr><td align="text" port="common" border="1">общий<br align="left"/></td></tr>
      <tr><td align="text" port="input"  border="1">вход<br align="left"/></td></tr>
    </table>
  >
]
!endprocedure

' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

!procedure $device_l_n_pe($title)
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td align="text" bgcolor="wheat"   border="1">$title</td></tr>
      <tr><td align="text" port="l" border="1">L<br align="left"/></td></tr>
      <tr><td align="text" port="n" border="1">N<br align="left"/></td></tr>
      <tr><td align="text" port="pe" border="1">PE<br align="left"/></td></tr>
    </table>
  >
]
!endprocedure

' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

!procedure $wall_outlet($title)
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td align="text" bgcolor="wheat"   border="1">$title</td></tr>
      <tr><td align="text" port="l1"  border="1">L<br align="left"/></td></tr>
      <tr><td align="text" port="l2"  border="1">L<br align="left"/></td></tr>
      <tr><td align="text" port="n1"  border="1">N<br align="left"/></td></tr>
      <tr><td align="text" port="n2"  border="1">N<br align="left"/></td></tr>
      <tr><td align="text" port="pe1" border="1">PE<br align="left"/></td></tr>
      <tr><td align="text" port="pe2" border="1">PE<br align="left"/></td></tr>
    </table>
  >
]
!endprocedure

' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

!procedure $switch_1p($title)
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td align="text" bgcolor="wheat"   border="1">$title</td></tr>
      <tr><td align="text" port="x1"  border="1">X1<br align="left"/></td></tr>
      <tr><td align="text" port="x2"  border="1">X2<br align="left"/></td></tr>
    </table>
  >
]
!endprocedure

' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

!procedure $switch_double($title, $key1="Клавиша 1", $key2="Клавиша 2")
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td colspan="3" align="text" border="1" bgcolor="lightgreen">$title</td></tr>

      <tr>
        <td colspan="1" rowspan="1" align="text" port="x1a"  border="1">X1A<br align="left"/></td>
        <td colspan="1" rowspan="2" border="1" bgcolor="lightgray">$key1</td>
        <td colspan="1" rowspan="1" align="text" port="y1a"  border="1">Y1A<br align="left"/></td>
      </tr>
      <tr>
        <td colspan="1" rowspan="1" align="text" port="x1b"  border="1">X1B<br align="left"/></td>
        <td colspan="1" rowspan="1" align="text" port="y1b"  border="1">Y1B<br align="left"/></td>
      </tr>

      <tr>
        <td colspan="1" rowspan="1" align="text" port="x2a"  border="1">X2A<br align="left"/></td>
        <td colspan="1" rowspan="2" border="1" bgcolor="lightgray">$key2</td>
        <td colspan="1" rowspan="1" align="text" port="y2a"  border="1">Y2A<br align="left"/></td>
      </tr>
      <tr>
        <td colspan="1" rowspan="1" align="text" port="x2b"  border="1">X2B<br align="left"/></td>
        <td colspan="1" rowspan="1" align="text" port="y2b"  border="1">Y2B<br align="left"/></td>
      </tr>
    </table>
  >
]
!endprocedure

' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

!procedure $light_fixture_single($title)
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td align="text" border="1" bgcolor="gold1">$title</td></tr>

      <tr>
        <td colspan="1" rowspan="1" align="text" port="pe" border="1">PE<br align="left"/></td>
      </tr>
      <tr>
        <td colspan="1" rowspan="1" align="text" port="n"  border="1">N<br align="left"/></td>
      </tr>
      <tr>
        <td colspan="1" rowspan="1" align="text" port="l" border="1">L<br align="left"/></td>
      </tr>
    </table>
  >
]
!endprocedure
' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

!procedure $light_fixture_double($title)
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td align="text" border="1" bgcolor="gold1">$title</td></tr>

      <tr>
        <td colspan="1" rowspan="1" align="text" port="l2" border="1">L2<br align="left"/></td>
      </tr>
      <tr>
        <td colspan="1" rowspan="1" align="text" port="pe" border="1">PE<br align="left"/></td>
      </tr>
      <tr>
        <td colspan="1" rowspan="1" align="text" port="n"  border="1">N<br align="left"/></td>
      </tr>
      <tr>
        <td colspan="1" rowspan="1" align="text" port="l1" border="1">L1<br align="left"/></td>
      </tr>
    </table>
  >
]
!endprocedure

' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

!procedure $led_strip($title)
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td align="text" border="1" bgcolor="lightgoldenrod1">$title</td></tr>

      <tr>
        <td colspan="1" rowspan="1" align="text" port="pos" border="1">+<br align="left"/></td>
      </tr>
      <tr>
        <td colspan="1" rowspan="1" align="text" port="neg" border="1">-<br align="left"/></td>
      </tr>

    </table>
  >
]
!endprocedure

' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

!procedure $power_supply($title)
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td colspan="2" align="text" border="1" bgcolor="mistyrose">$title</td></tr>

      <tr>
        <td colspan="1" rowspan="1" align="text" port="pos"  border="1">+<br align="left"/></td>
        <td colspan="1" rowspan="1" align="text" port="l"    border="1">L<br align="left"/></td>
      </tr>

      <tr>
        <td colspan="1" rowspan="1" align="text" port="neg"  border="1">-<br align="left"/></td>
        <td colspan="1" rowspan="1" align="text" port="n"    border="1">N<br align="left"/></td>
      </tr>

      <tr>
        <td colspan="1" rowspan="1" align="text" port="shield"   border="1"> <br align="left"/></td>
        <td colspan="1" rowspan="1" align="text" port="pe"       border="1">PE<br align="left"/></td>
      </tr>

    </table>
  >
]
!endprocedure

' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

!procedure $ventilator()
[
  shape = none
  fontname="Courier"
  label = <
    <table border="0" cellspacing="0">
      <tr><td colspan="1" align="text" border="1" bgcolor="lightskyblue1">Вентилятор</td></tr>

      <tr>
        <td colspan="1" rowspan="1" align="text" port="l"    border="1">L<br align="left"/></td>
      </tr>

      <tr>
        <td colspan="1" rowspan="1" align="text" port="n"    border="1">N<br align="left"/></td>
      </tr>

      <tr>
        <td colspan="1" rowspan="1" align="text" port="pe"       border="1">PE<br align="left"/></td>
      </tr>

      <tr>
        <td colspan="1" rowspan="1" align="text" port="light"       border="1">свет<br align="left"/></td>
      </tr>

    </table>
  >
]
!endprocedure

' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

@enduml
